services:
  conneckseek:
    image: chat_us
    command: python /app/manage.py runserver 0.0.0.0:8000
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app 
    ports:
      - 8000:8000
    depends_on: