services:

  chat_us:
    image: chat_us
    command: python /app/manage.py runserver 0.0.0.0:8000
    # command: python /app/manage.py makemigrations
    # command: python /app/manage.py migrate
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STUN_SERVER_URL=stun:3.94.179.169:3478
      - STUN_SERVER_USERNAME=burhan
      - STUN_SERVER_CREDENTIALS=12345678
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    volumes:
      - ./:/app 
    ports:
      - 8000:8000
    depends_on:
      - db

  redis:
    image: redis:alpine
    restart: always
    # ports:
    #   - 6379:6379

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres